// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uifhgqqvaurazpaxpfnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpZmhncXF2YXVyYXpwYXhwZm5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMDE3NDUsImV4cCI6MjA3NDY3Nzc0NX0.2rJ-s0ny7Cjj1AVpjLcSv2dGAOUk55gM7s1efVdziqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});